spring.application.name: simpleApplication
camunda:
  bpm:
    datasource:
      jdbcUrl: jdbc:h2:mem:camundaDB;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      platform: h2
      username: sa
      password: sa
      schema-update: true
    application:
      delete-upon-undeploy: false
      scan-for-process-definitions: false
      deploy-changed-only: true
      resume-previous-versions: true
      resume-previous-by: a value
    job-execution:
      enabled: true
    metrics:
      enabled: true
db-reporter-activate: false